version: '3.1'
services:
  mysql:
    image: 'mysql-server:latest'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=sample
      - MYSQL_USER=user
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  java:
    image: sample-java-jdbc:latest
    environment:
      - MYSQL_URL=jdbc:mysql://mysql:3306/sample
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user